// Package auth holds the pieces that prove a *person* is who they say they
// are: password hashing and session tokens. Machine credentials — the
// aperture keys agents use — live in internal/storage and are a different
// problem: they are generated by us, never chosen by a human, and never
// reused across sites.
package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"runtime"
	"strings"

	"golang.org/x/crypto/argon2"
)

// Password rules. The upper bound is not a policy but a defence: hashing is
// deliberately expensive, so an unbounded password is an unbounded amount of
// work for anyone who can reach the login form.
const (
	MinPasswordLen = 10
	MaxPasswordLen = 1024
)

// argon2id parameters. Memory dominates the cost for an attacker with GPUs,
// which is the case these numbers are chosen for; they are stored with every
// hash, so raising them later does not invalidate existing passwords.
const (
	argonTime    = 3
	argonMemory  = 64 * 1024 // KiB
	argonKeyLen  = 32
	argonSaltLen = 16
)

var (
	// ErrPasswordTooShort and ErrPasswordTooLong are policy failures, safe to
	// show to whoever is typing.
	ErrPasswordTooShort = fmt.Errorf("password must be at least %d characters", MinPasswordLen)
	ErrPasswordTooLong  = fmt.Errorf("password must be at most %d characters", MaxPasswordLen)
	// ErrHashFormat means the stored hash is not one we can read — corrupted
	// row, or a hash from a scheme this build does not know.
	ErrHashFormat = errors.New("unrecognised password hash")
)

// argonThreads keeps the cost predictable on small machines: the gateway is
// expected to run on one or two cores next to everything else.
func argonThreads() uint8 {
	n := runtime.NumCPU()
	if n > 4 {
		n = 4
	}
	return uint8(n)
}

// HashPassword returns a PHC-formatted argon2id hash, parameters included.
func HashPassword(password string) (string, error) {
	if len(password) < MinPasswordLen {
		return "", ErrPasswordTooShort
	}
	if len(password) > MaxPasswordLen {
		return "", ErrPasswordTooLong
	}

	salt := make([]byte, argonSaltLen)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("read salt: %w", err)
	}
	threads := argonThreads()
	key := argon2.IDKey([]byte(password), salt, argonTime, argonMemory, threads, argonKeyLen)

	return fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s",
		argon2.Version, argonMemory, argonTime, threads,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key),
	), nil
}

// VerifyPassword reports whether the password matches the stored hash. The
// comparison is constant time, and the parameters come from the hash rather
// than from the constants above, so old hashes keep working after a change.
func VerifyPassword(encoded, password string) (bool, error) {
	params, salt, want, err := decodeHash(encoded)
	if err != nil {
		return false, err
	}
	got := argon2.IDKey([]byte(password), salt, params.time, params.memory, params.threads, uint32(len(want)))
	return subtle.ConstantTimeCompare(got, want) == 1, nil
}

// NeedsRehash reports whether a stored hash was made with weaker parameters
// than the current ones, so it can be upgraded on the next successful login.
func NeedsRehash(encoded string) bool {
	params, _, _, err := decodeHash(encoded)
	if err != nil {
		return true
	}
	return params.memory < argonMemory || params.time < argonTime
}

// dummyHash is verified against when no user matches, so that "no such user"
// and "wrong password" cost the same. Without it the login form answers
// faster for addresses that are not registered, which is an enumeration
// oracle for anyone with a stopwatch.
var dummyHash, _ = HashPassword(strings.Repeat("x", MinPasswordLen))

// SpendVerifyTime burns the same work a real verification would, for the case
// where there is nothing to verify against.
func SpendVerifyTime() {
	_, _ = VerifyPassword(dummyHash, "not the password")
}

type argonParams struct {
	memory  uint32
	time    uint32
	threads uint8
}

func decodeHash(encoded string) (argonParams, []byte, []byte, error) {
	parts := strings.Split(encoded, "$")
	// "", "argon2id", "v=19", "m=...,t=...,p=...", salt, hash
	if len(parts) != 6 || parts[1] != "argon2id" {
		return argonParams{}, nil, nil, ErrHashFormat
	}

	var version int
	if _, err := fmt.Sscanf(parts[2], "v=%d", &version); err != nil || version != argon2.Version {
		return argonParams{}, nil, nil, ErrHashFormat
	}

	var p argonParams
	if _, err := fmt.Sscanf(parts[3], "m=%d,t=%d,p=%d", &p.memory, &p.time, &p.threads); err != nil {
		return argonParams{}, nil, nil, ErrHashFormat
	}
	if p.memory == 0 || p.time == 0 || p.threads == 0 {
		return argonParams{}, nil, nil, ErrHashFormat
	}

	salt, err := base64.RawStdEncoding.Strict().DecodeString(parts[4])
	if err != nil || len(salt) == 0 {
		return argonParams{}, nil, nil, ErrHashFormat
	}
	key, err := base64.RawStdEncoding.Strict().DecodeString(parts[5])
	if err != nil || len(key) == 0 {
		return argonParams{}, nil, nil, ErrHashFormat
	}
	return p, salt, key, nil
}
